/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gestioncitas.vista;

import com.gestioncitas.entidad.Cita;
import com.gestioncitas.entidad.Paciente;
import com.gestioncitas.interfaces.DAOPacienteMetodos;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class FrmGestionCitas extends javax.swing.JFrame {

    /**
     * Creates new form FrmGestionCitas
     */
    public FrmGestionCitas() throws Exception {
        
        initComponents();
        DAOPacienteMetodos metodos = new DAOPacienteMetodos();
        metodos.mostrar(jtreporte);
        
        Image img=Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/regresar.png"));
        btnregresar.setIcon (new ImageIcon (img.getScaledInstance (btnregresar.getWidth(), btnregresar.getHeight(), Image.SCALE_SMOOTH)));
        this.setIconImage (img);
        this.setLocationRelativeTo(null);
        
        
        //BOTON SALIDA
        Image imgS=Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/salida.png"));
        btnsalida.setIcon (new ImageIcon (imgS.getScaledInstance (btnsalida.getWidth(), btnsalida.getHeight(), Image.SCALE_SMOOTH)));
        this.setIconImage (imgS);
        this.setLocationRelativeTo(null);
        
        jtreporte.getTableHeader().setFont(new Font("Segue UI", Font.BOLD,12));
        jtreporte.getTableHeader().setOpaque(false);
        jtreporte.getTableHeader().setBackground(new Color(31,111,209));
        jtreporte.getTableHeader().setForeground(new Color(255,255,255));
        jtreporte.setRowHeight(25);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtdni = new javax.swing.JTextField();
        txtnombres = new javax.swing.JTextField();
        txtapelpaterno = new javax.swing.JTextField();
        txtapelmaterno = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtreporte = new javax.swing.JTable();
        btnnuevo1 = new javax.swing.JButton();
        btnregistrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnregresar = new javax.swing.JButton();
        btnsalida = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel7.setText("Nombres:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        jLabel8.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel8.setText("Apellido paterno:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jLabel9.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel9.setText("Apellido materno:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        jLabel10.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel10.setText("Dirección:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, -1, -1));

        jLabel11.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel11.setText("Teléfono:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, -1, -1));

        txtdni.setBackground(new java.awt.Color(153, 153, 153));
        txtdni.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtdni, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 230, 30));

        txtnombres.setBackground(new java.awt.Color(153, 153, 153));
        txtnombres.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtnombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 230, 30));

        txtapelpaterno.setBackground(new java.awt.Color(153, 153, 153));
        txtapelpaterno.setForeground(new java.awt.Color(255, 255, 255));
        txtapelpaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapelpaternoActionPerformed(evt);
            }
        });
        jPanel1.add(txtapelpaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 230, 30));

        txtapelmaterno.setBackground(new java.awt.Color(153, 153, 153));
        txtapelmaterno.setForeground(new java.awt.Color(255, 255, 255));
        txtapelmaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapelmaternoActionPerformed(evt);
            }
        });
        jPanel1.add(txtapelmaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 230, 30));

        txtdireccion.setBackground(new java.awt.Color(153, 153, 153));
        txtdireccion.setForeground(new java.awt.Color(255, 255, 255));
        txtdireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdireccionActionPerformed(evt);
            }
        });
        jPanel1.add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 200, 30));

        txttelefono.setBackground(new java.awt.Color(153, 153, 153));
        txttelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelefonoActionPerformed(evt);
            }
        });
        jPanel1.add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 200, 30));

        btnbuscar.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        btnbuscar.setText("Buscar paciente");
        jPanel1.add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 210, 150, -1));

        btneliminar.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        btneliminar.setText("Eliminar");
        jPanel1.add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 150, -1));

        btnactualizar.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        btnactualizar.setText("Actualizar");
        jPanel1.add(btnactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, 150, -1));

        jLabel12.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel12.setText("DNI:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jtreporte.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jtreporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtreporte.setRowHeight(30);
        jtreporte.setSelectionBackground(new java.awt.Color(255, 102, 102));
        jtreporte.setShowHorizontalLines(true);
        jtreporte.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtreporte);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 590, 180));

        btnnuevo1.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        btnnuevo1.setText("Nuevo registro");
        jPanel1.add(btnnuevo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 160, 150, -1));

        btnregistrar.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        btnregistrar.setText("Registrar");
        btnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 150, -1));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jLabel6.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("REGISTRO DE PACIENTE");

        btnregresar.setBackground(new java.awt.Color(204, 204, 255));
        btnregresar.setFont(new java.awt.Font("Segoe UI", 0, 1)); // NOI18N
        btnregresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/regresar.png"))); // NOI18N
        btnregresar.setBorder(null);
        btnregresar.setContentAreaFilled(false);
        btnregresar.setMargin(new java.awt.Insets(2, 10, 3, 4));
        btnregresar.setMaximumSize(new java.awt.Dimension(150, 150));
        btnregresar.setMinimumSize(new java.awt.Dimension(100, 100));
        btnregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresarActionPerformed(evt);
            }
        });

        btnsalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salida.png"))); // NOI18N
        btnsalida.setBorderPainted(false);
        btnsalida.setContentAreaFilled(false);
        btnsalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnsalida, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 336, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(242, 242, 242)
                .addComponent(btnregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsalida, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 70));

        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel1.setText("Datos Personales");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 955, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefonoActionPerformed

    private void txtdireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdireccionActionPerformed

    private void txtapelmaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapelmaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapelmaternoActionPerformed

    private void txtapelpaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapelpaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapelpaternoActionPerformed

    private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarActionPerformed
        
        DAOPacienteMetodos metodos = new DAOPacienteMetodos();
        Paciente paciente = new Paciente();
        Cita cita = new Cita();
        
        String dni = txtdni.getText();
        String nombres = txtnombres.getText();
        String apel_paterno = txtapelpaterno.getText();
        String apel_materno = txtapelmaterno.getText();
        String direccion = txtdireccion.getText();
        String telefono = txttelefono.getText();
        
        paciente.setDni(dni);
        paciente.setNombres(nombres);
        paciente.setApel_paterno(apel_paterno);
        paciente.setApel_materno(apel_materno);
        paciente.setDireccion(direccion);
        paciente.setTelefono(telefono);
        cita.setId_cita(WIDTH);
        
        try {
            metodos.registrar(paciente, cita);
            metodos.mostrar(jtreporte);
        } catch (Exception ex) {
            Logger.getLogger(FrmGestionCitas.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtdni.setText("");
        txtnombres.setText("");
        txtapelpaterno.setText("");
        txtapelmaterno.setText("");
        txtdireccion.setText("");
        txttelefono.setText("");
        txtdni.requestFocus();
        
    }//GEN-LAST:event_btnregistrarActionPerformed

    private void btnregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresarActionPerformed

        
       try {
            Inicio ventana = new Inicio();
            ventana.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(FrmGestionCitas.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }//GEN-LAST:event_btnregresarActionPerformed

    private void btnsalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalidaActionPerformed

        try {
            int confirmacion = JOptionPane.showOptionDialog(this, "¿Estás seguro de salir?", "Confirmar salida", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"Sí", "No"}, "No");
            if (confirmacion == JOptionPane.YES_OPTION) {
                Login ventana = new Login();
                ventana.setVisible(true);
                this.dispose();
            }
        } catch (Exception ex) {
            Logger.getLogger(FrmGestionCitas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnsalidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGestionCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGestionCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGestionCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGestionCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrmGestionCitas().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(FrmGestionCitas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnnuevo1;
    private javax.swing.JButton btnregistrar;
    private javax.swing.JButton btnregresar;
    private javax.swing.JButton btnsalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtreporte;
    private javax.swing.JTextField txtapelmaterno;
    private javax.swing.JTextField txtapelpaterno;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtdni;
    private javax.swing.JTextField txtnombres;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
