/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gestioncitas.vista;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
                //iMAGEN CITA
        initComponents();
        Image img=Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/cita.png"));
        lblcita.setIcon (new ImageIcon (img.getScaledInstance (lblcita.getWidth(), lblcita.getHeight(), Image.SCALE_SMOOTH)));
        this.setIconImage (img);
        this.setLocationRelativeTo(null);
        
         //iMAGEN MEDICO
        Image imgM=Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/medico.png"));
        lblmedico.setIcon (new ImageIcon (imgM.getScaledInstance (lblmedico.getWidth(), lblmedico.getHeight(), Image.SCALE_SMOOTH)));
        this.setIconImage (imgM);
        this.setLocationRelativeTo(null);
        
        //iMAGEN horario
        Image imgC=Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/horario.png"));
        lblhorario.setIcon (new ImageIcon (imgC.getScaledInstance (lblhorario.getWidth(), lblhorario.getHeight(), Image.SCALE_SMOOTH)));
        this.setIconImage (imgC);
        this.setLocationRelativeTo(null);
        
        //iMAGEN PACIENTE
        Image imgP=Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/paciente.png"));
        lblpaciente.setIcon (new ImageIcon (imgP.getScaledInstance (lblpaciente.getWidth(), lblpaciente.getHeight(), Image.SCALE_SMOOTH)));
        this.setIconImage (imgP);
        this.setLocationRelativeTo(null);

        //BOTON SALIDA
        Image imgS=Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/salida.png"));
        btnsalida.setIcon (new ImageIcon (imgS.getScaledInstance (btnsalida.getWidth(), btnsalida.getHeight(), Image.SCALE_SMOOTH)));
        this.setIconImage (imgS);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblpaciente = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblhorario = new javax.swing.JLabel();
        lblmedico = new javax.swing.JLabel();
        lblcita = new javax.swing.JLabel();
        btnpaciente = new javax.swing.JButton();
        btnhorario = new javax.swing.JButton();
        btnmedico = new javax.swing.JButton();
        btncitas = new javax.swing.JButton();
        btnsalida = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblpaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/medico.png"))); // NOI18N
        lblpaciente.setText("jLabel2");
        jPanel1.add(lblpaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 330, 310));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 70)); // NOI18N
        jLabel3.setText("CLINICA ODONTOLOGICA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, -1));

        lblhorario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/horario.png"))); // NOI18N
        lblhorario.setMaximumSize(new java.awt.Dimension(607, 442));
        lblhorario.setMinimumSize(new java.awt.Dimension(607, 442));
        lblhorario.setPreferredSize(new java.awt.Dimension(607, 442));
        jPanel1.add(lblhorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 360, 360));

        lblmedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/medico.png"))); // NOI18N
        lblmedico.setMaximumSize(new java.awt.Dimension(607, 442));
        lblmedico.setMinimumSize(new java.awt.Dimension(607, 442));
        lblmedico.setPreferredSize(new java.awt.Dimension(607, 442));
        jPanel1.add(lblmedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 340, 390, 300));

        lblcita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cita.png"))); // NOI18N
        lblcita.setMaximumSize(new java.awt.Dimension(607, 442));
        lblcita.setMinimumSize(new java.awt.Dimension(607, 442));
        lblcita.setPreferredSize(new java.awt.Dimension(607, 456));
        jPanel1.add(lblcita, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 340, 360, 300));

        btnpaciente.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        btnpaciente.setText("Paciente");
        btnpaciente.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.SystemColor.textHighlight, null));
        btnpaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpacienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnpaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 700, 240, -1));

        btnhorario.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        btnhorario.setText("Horario");
        btnhorario.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.SystemColor.textHighlight));
        btnhorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhorarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnhorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 700, 240, 70));

        btnmedico.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        btnmedico.setText("Medico");
        btnmedico.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.SystemColor.textHighlight));
        btnmedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmedicoActionPerformed(evt);
            }
        });
        jPanel1.add(btnmedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 700, 240, -1));

        btncitas.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        btncitas.setText("Citas");
        btncitas.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.SystemColor.textHighlight));
        btncitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncitasActionPerformed(evt);
            }
        });
        jPanel1.add(btncitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 700, 240, -1));

        btnsalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salida.png"))); // NOI18N
        btnsalida.setBorderPainted(false);
        btnsalida.setContentAreaFilled(false);
        btnsalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalidaActionPerformed(evt);
            }
        });
        jPanel1.add(btnsalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inicio.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1610, 810));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1610, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnpacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpacienteActionPerformed
        try {
            FrmGestionCitas ventana = new FrmGestionCitas();
            ventana.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(FrmGestionCitas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnpacienteActionPerformed

    private void btnhorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhorarioActionPerformed
          try {
            VistaHorarios ventana = new VistaHorarios();
            ventana.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(VistaHorarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnhorarioActionPerformed

    private void btnmedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmedicoActionPerformed
    try {
            VistaMedicos ventana = new VistaMedicos();
            ventana.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(VistaMedicos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnmedicoActionPerformed

    private void btncitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncitasActionPerformed
             try {
            VistaCita ventana = new VistaCita();
            ventana.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(VistaCita.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btncitasActionPerformed

    private void btnsalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalidaActionPerformed


try {
    int confirmacion = JOptionPane.showOptionDialog(this, "¿Estás seguro de salir?", "Confirmar salida", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"Sí", "No"}, "No");
    if (confirmacion == JOptionPane.YES_OPTION) {
        Login ventana = new Login();
        ventana.setVisible(true);
        this.dispose();
    }
} catch (Exception ex) {
    Logger.getLogger(FrmGestionCitas.class.getName()).log(Level.SEVERE, null, ex);
}
    }//GEN-LAST:event_btnsalidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncitas;
    private javax.swing.JButton btnhorario;
    private javax.swing.JButton btnmedico;
    private javax.swing.JButton btnpaciente;
    private javax.swing.JButton btnsalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblcita;
    private javax.swing.JLabel lblhorario;
    private javax.swing.JLabel lblmedico;
    private javax.swing.JLabel lblpaciente;
    // End of variables declaration//GEN-END:variables
}
